### ISSUE TITLE
Sentry Error Adding.

### ISSUE THREAD

**Issue by xIGBClutchIx** [kryptco/kr-u2f#1]
Everytime I try to add Sentry U2F I get "Error adding U2F (Universal 2nd Factor) authenticator" on their site and does not actually go through. And in the console I get `POST https://sentry.io/api/0/users/me/authenticators/u2f/enroll/ 500 (INTERNAL SERVER ERROR)`.

On the Krypton end it looks to register but without the icon. [Example](https://i.clutchy.me/g88vvxC7.PNG)

**Comment by kcking** [comment]
Thank you for reporting -- we will have a fix for this released later today

**Comment by kcking** [comment]
This has been fixed in version 1.0.3 which will be rolling out in the next couple of hours. Let us know if you have any other issues!

**Comment by xIGBClutchIx** [comment]
Awesome just tested it out seems to be good now! :)
Is there anyway to get rid of the old entry without the logo on the app side? [Example](https://i.clutchy.me/uRqsG3N7.PNG) @kcking
