### ISSUE TITLE
Error when adding key to AWS account

### ISSUE THREAD

**Issue by victorluft** [kryptco/kr-u2f#11]
Amazon finally added [U2F support for IAM users](https://aws.amazon.com/blogs/security/use-yubikey-security-key-sign-into-aws-management-console/), but it looks like something about their implementation is incompatible with Krypton currently – when I try to add the a Krypton key, iOS app says it's registered successfully and Amazon says.

```
Unexpected error
An unexpected error occurred.
Attestation Certificate is not valid.
```

This is Chromium 69.0.3497.100 on Linux, let me know if you need any other system details.

(I did successfully enroll a Yubikey on the same browser & account, fwiw.)

**Comment by kcking** [comment]
It looks like AWS only supports Yubikeys. Google's Titan keys are failing with the same error. AWS will have to relax their attestation policy in order to support keys from other manufacturers / Krypton.

**Comment by victorluft** [comment]
That’s unfortunate, but I guess not that surprising given their generally poor mfa implementation choices. Thanks for looking into it – big fan of Krypton and have been using it since release. Hopefully y’all will let me pay money for it at some point. 😉

**Comment by JonahAragon** [comment]
Just because nobody's commented on this issue since, [AWS now supports non-YubiKey keys](https://aws.amazon.com/blogs/security/use-yubikey-security-key-sign-into-aws-management-console/) (and I have Krypton configured on my AWS account):

> **Update on October 8, 2018:** After we launched support for security devices manufactured by Yubico on September 25, 2018, we received feedback from customers to support other U2F security key providers, as well. Starting October 8, 2018, you can now enable other U2F security keys as an MFA device for your root and IAM users.

**Comment by victorluft** [comment]
Thanks for the info. I'm successfully using Krypton now, so I'll go ahead and close this issue.

**Comment by Vlaaaaaaad** [comment]
Note that this is not supported on Safari with the Krypt.co plugin. I imagine it's because of [this](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_mfa_u2f_supported_configurations.html?icmpid=docs_iam_console):
> AWS currently supports only browsers that natively support the U2F standard. AWS does not support using plugins to add U2F browser support. Also note that some browser plugins are incompatible with the U2F standard and can cause unexpected results with U2F security keys.
