### ISSUE TITLE
Are you also going publish the safari extension in the App Store?

### ISSUE THREAD

**Issue by mura-admin** [kryptco/kr-u2f#12]
Now that the extension gallery is being deprecated and will be removed (next release?) are you also going publish the extension in the App Store?

**Comment by mura-admin** [comment]
Ignore previous comment about the safari source code, for some reason when I search for "safari" it didn't show anything

**Comment by mura-admin** [comment]
One odd thing I noticed as well about the safari extension is that if you follow the link from the website it does not show an install option. However if you refresh or paste the link directly it does show the install icon.

**Comment by mura-admin** [comment]
I think this is a bug in the extension gallery. It seems to be a naming collision between SafariContentExtensionGalleryController and SafariPushNotification. For some reason it uses the correct SafariContentExtensionGalleryController on refresh.

**Comment by kcking** [comment]
Closing this for now as it seems to be an intermittent issue on Apple's end

**Comment by jeremy** [comment]
Safari Technology Preview Release 80 just disabled legacy extensions today, FYI. Will need an app store release to continue using Krypton with it. (Desirable since Tech Preview is great for web app dev against future-Safari webauthn/u2f support.)

**Comment by jeremy** [comment]
Safari 13 (coming with macOS Catalina) no longer supports Krypton.

**Comment by jeremy** [comment]
Moved to #38
