### ISSUE TITLE
AWS Console is not functional in several places with firefox extension enabled

### ISSUE THREAD

**Issue by sra** [kryptco/kr-u2f#13]
I recently switched from chrome to firefox and in the AWS console, there are several screens that fail to load when the extension is enabled.

This message appears in the browser console (url: https://console.aws.amazon.com/rds/home?region=us-east-1# )

```
TypeError: cannot declare global binding `u2f': property must be configurable or both writable and enumerable home:1:1
<anonymous> rds-40.js:1:1 rds/rds.__installRunAsyncCode
https://dado4e41kbenk.cloudfront.net/fb5ab38edbb6807d6e20c2a5de2c290a97c4370f/rds/rds.nocache.js:11:163
__gwtInstallCode https://console.aws.amazon.com/rds/home#:1:526
o7j https://console.aws.amazon.com/rds/home#:57:31
M7j https://console.aws.amazon.com/rds/home#:245:39
<anonymous> https://console.aws.amazon.com/rds/home#:130:64
_6j https://console.aws.amazon.com/rds/home#:189:28
c7j https://console.aws.amazon.com/rds/home#:20:60
b7j/< https://console.aws.amazon.com/rds/home#:146:48
<anonymous> https://dado4e41kbenk.cloudfront.net/fb5ab38edbb6807d6e20c2a5de2c290a97c4370f/rds/deferredjs/5F178518CC64B37ED525028D41CE5E33/40.cache.js:1:1
```

Disabling the extension fixes the error. I'm not using u2f with AWS at the moment.

**Comment by kcking** [comment]
Thank you for reporting this. I'm having trouble reproducing (on the RDS homepage in us-east-1 as well), which version of firefox/the krypton extension are you using?

**Comment by kcking** [comment]
Ok I am running the same. Out of curiosity, does this still happen after clearing your cache?

"Secured" status for accounts is not yet automatically synced. Re-pairing should refresh the status in the browser extension.

**Comment by sra** [comment]
I disabled all other extensions, just in case there was a conflict and restarted but the error persists. Is there any other diagnostic I can provide?

**Comment by kcking** [comment]
Version 1.0.11 of the FF extension has been released and should resolve this issue. Thanks again for reporting!
