### ISSUE TITLE
Firefox addon changes colors of unrelated website

### ISSUE THREAD

**Issue by Spferical** [kryptco/kr-u2f#14]
With the Firefox extension version v1.0.11 installed on Firefox 62.0.3 on Linux, some elements on https://pleroma.site become the green Krypton color. This happens with a fresh Firefox profile. It does not happen with the Chrome extension.
Without Krypton:
![without_krypton](https://user-images.githubusercontent.com/6250054/46587648-51538f00-ca5d-11e8-9bd4-f63d11a7fde8.png)
With Krypton:
![with_krypton](https://user-images.githubusercontent.com/6250054/46587650-531d5280-ca5d-11e8-9bbc-723914261430.png)

**Comment by kcking** [comment]
Thanks for reporting! It turns out our injected CSS used the same color variables (`--fg` and `-- bg`) as pleroma. This will be fixed in the next release.

**Comment by kcking** [comment]
This should be fixed in version 1.0.12. Thanks again!
