### ISSUE TITLE
Failed to pair

### ISSUE THREAD

**Issue by yaakovfeldman** [kryptco/kr-u2f#16]
I installed the chrome extension and scanned it with the android app. The android app said that it paired but the chrome extension still shows the QR code. I then tried the firefox extension, with the same result.

I'm using the latest versions from the respective app stores and am not behind a proxy.

Android app is v2.5.4.

**Comment by brentkirkland** [comment]
same issue here for latest ios

**Comment by kcking** [comment]
We published some pairing-related fixes yesterday in extension version 1.0.14. Please make sure you're up to date and let us know if you're still having issues.

**Comment by brentkirkland** [comment]
@kcking works for me now! Thanks :)

**Comment by yaakovfeldman** [comment]
@kcking I am uisng extension v1.0.14 but still won't pair.

**Comment by kcking** [comment]
We have fixed an issue with pairing in the android app and released the fix with version 2.5.5 of the app. Please update and let us know if this has solved the issue.

**Comment by yaakovfeldman** [comment]
@kcking Installed new version of app and it paired. Thanks
