### ISSUE TITLE
U2F device not always recognised in Safari

### ISSUE THREAD

**Issue by mura-admin** [kryptco/kr-u2f#17]
I've noticed that on a custom install of Gitlab, and presumably Gitlab itself, the U2F device is not recognised on first page load. If I press command-option-R, on refresh the "setup U2F device" will appear. The same issue occurs on login. A hard refresh seems to be the workaround. 

Could this be an issue with the order the javascript is executed in? Running on Safari 12 on MacOS Mojave, krypt.co version 1.0.8

**Comment by agrinman** [comment]
Closing in favor of #38
