### ISSUE TITLE
It seems that twitter U2F URL has changed

### ISSUE THREAD

**Issue by r2qokk** [kryptco/kr-u2f#22]
It keeps saying
```URL address not supported. Please try again with a valid twitter.com URL.```
while add a key or logging

**Comment by kcking** [comment]
Seems to be working fine on Firefox. Which browser are you using?

**Comment by r2qokk** [comment]
Firefox 65.0 64-bit on Ubuntu 18.04.2 LTS
However, GitHub works fine.

**Comment by agrinman** [comment]
Twitter switched to WebAuthn -- best bet is to make sure you've re-registered your key.
