### ISSUE TITLE
Okta support

### ISSUE THREAD

**Issue by mateusz-fiolka** [kryptco/kr-u2f#23]
The website advertises support for `Okta` (or `Okta` support for `u2f`). I tried to set it up, but the only `u2f` option there is related to using `yubikey`. 

I thought - whatever, I'll try anyway, but then I get a form requesting me to type some pin or keycode, which I have no idea how to generate with the `Firefox` addon or `Krypton` app.

I set `AWS` integration before with the same software stack, so it seems that the problem is somewhere else.

Also tried with `Chrome` with the same result.

**Comment by agrinman** [comment]
Okta supports two types of yubikeys as far as I know: OTP and U2F. OTP is actually code based and phishable and not supported by Krypton. U2F is not phishable and **is supported by Krypton**. Make sure you've enabled U2F!
