### ISSUE TITLE
Safari extension doesn't work (and is old)

### ISSUE THREAD

**Issue by brainsik** [kryptco/kr-u2f#24]
Hello. The Safari extension is not recognized by any site I visit. It also appears [the version in the Extensions Gallery](https://safari-extensions.apple.com/details/?id=co.krypt.krypton.u2f-W7AMYM5LPN) is rather old: v1.0.8. I see the v1.0.9 release notes say "Finish Safari extension", so, perhaps this is the issue?

Is there a newer version I can download and try?

<img width="495" alt="Krypton extension 1.0.8" src="https://user-images.githubusercontent.com/162998/55502854-56575c80-5602-11e9-846a-7cc93033d7a9.png">

<img width="316" alt="GitHub - This browser doesn’t support security keys" src="https://user-images.githubusercontent.com/162998/55502773-3031bc80-5602-11e9-9ec8-d60cb204fefe.png">

**Comment by agrinman** [comment]
Try setting your browser agent to chrome
