### ISSUE TITLE
1password 

### ISSUE THREAD

**Issue by FernandoMiguel** [kryptco/kr-u2f#33]
Add support for 1password
https://blog.1password.com/introducing-support-for-u2f-security-keys/

**Comment by agrinman** [comment]
It should work, what error are you getting?

**Comment by FernandoMiguel** [comment]
@agrinman no error. Just don't see it in the list of supported apps.
Since 1password just made the announcement, I thought it would be a good idea to track it with kr

If you say it should work, we can close this ticket.

I'll give it a try with some of our devs and report any issues we may find.

**Comment by agrinman** [comment]
I've tested it, it looks like everything is working just fine for me. Yes, we can add as a known facet to Krypton, thanks.
