### ISSUE TITLE
Pairing Mac desktop app with Android app failing

### ISSUE THREAD

**Issue by dimitrisch** [kryptco/kr-u2f#46]
I'm trying to pair the new Mac desktop app with my Android phone.
The phone is a Xiaomi Mi Mix 2, running Android 9, app version 2.5.5. The Mac is on 10.14.6 (unsupported), app version 1.1.
On the Android side things seem ok, with the device appearing paired but on the Mac side I'm consistently getting this notification:
> Pairing Failed
> Could not complete pairing process.
> Missing dictionary key: public_key_wire

Deleting and reinstalling, rebooting, removing all app related files with AppCleaner don't help.
Firefox pairing works correctly. 
The attached file are the relevant errors (I think) from system log.
[krypton-error.log](https://github.com/kryptco/kr-u2f/files/4617303/krypton-error.log)

**Comment by agrinman** [comment]
Yep, can confirm this an issue. Will fix it shortly.

In the meantime you can easily fix this for yourself by enabling developer mode in Krypton (you can disable it afterwards). Then pairing should work.

**Comment by agrinman** [comment]
Should be fixed in v1.2 on the Mac app just released
