### ISSUE TITLE
Firefox addon doesn't work for Google accounts

### ISSUE THREAD

**Issue by thewan056** [kryptco/kr-u2f#7]
Per title, attempting to do so displays a pop up asking me to use Chrome.

**Comment by kcking** [comment]
Thanks for reporting. Currently Google does not support registering on Firefox, but logging in does work. We are working on a potential workaround while Google adds support for Firefox U2F

**Comment by thewan056** [comment]
This clears it up, thanks. Hopefully you could add this information to your FAQ on your website, or to the Firefox Addon page as I wondering if I was doing something wrong, or maybe I had another addon conflicting with Krypton.

**Comment by CiraciNicolo** [comment]
Neither Safari works, also Github doesn't detect the fake device.

**Comment by kcking** [comment]
Only Chrome can currently register security keys with Google, but they are working on adding support for other browsers as well. @CiraciNicolo if you are having an issue with Safari on GitHub (which is currently supported) it would be great if you could provide more detail in a separate issue.

**Comment by CiraciNicolo** [comment]
@kcking Thanks for the update. About GitHub, well, I retried and it worked. Sorry for the trouble

**Comment by agrinman** [comment]
I believe all these should work now, closing. Please re-open if this is not the case...
