### ISSUE TITLE
Adding a website seems impossible

### ISSUE THREAD

**Issue by Frazew** [kryptco/kr-u2f#8]
I generally know my way around things, but here either the UI is terrible or I'm missing something big as I cannot seem to find how to add just about *any* website to Krypton.
I'm using the extension on Firefox and it is paired with my Android phone.
Upon configuring 2FA on any service supported by Krypton, there is no way to either scan the QR Code from the website in the Krypton app or enter the key anywhere.

I genuinely think that the UI should be improved as this makes it impossible for anyone to figure it out.

**Comment by agrinman** [comment]
Hi @Frazew -- sorry for any confusion. Most websites require you to add another form of two-factor like SMS or TOTP before you can add a security key. Krypton does not support TOTP codes currently.

Once you setup a two-factor backup mechanism, tap the shortcut in the browser extension to "Add a Security Key" to your account.

**Comment by Frazew** [comment]
Oh right! I guess I should have done more reading before submitting an issue here.

Thanks for the clarification !
