### ISSUE TITLE
Add support for Safari

### ISSUE THREAD

**Issue by cdmmultimedia** [kryptco/kr-u2f#9]
Could you use [this polyfill](https://www.google.fr/search?q=FIDO+support+safari&oq=fido+&aqs=chrome.0.69i59j69i57j69i60l2j69i61.1388j0j7&sourceid=chrome&ie=UTF-8) while we wait for Apple to implement U2F on Safari for mac OS? This would shorten the time needed to Have Krypton working on Safari.
We're willing to work on this one if you guys would accept a PR later.

**Comment by agrinman** [comment]
We have Safari support -- we're waiting for Apple to approve the safari extension. Hopefully it will be out very shortly!

**Comment by cdmmultimedia** [comment]
Is there any way to build the extension on my computer and build it, while we wait for apple to approve it?

**Comment by cdmmultimedia** [comment]
Okay, well it was easy:
- Clone the repo
- Install the dependencies with `yarn`
- Build the extension with `make build`
- Load the extension in Safari using Extension Builder
- Run the extension

I feel dumb! Thank you for making this nice product!

**Comment by kcking** [comment]
Great to hear you got it working!

**Comment by cro** [comment]
Any status on this?
